openapi: 3.0.0
info:
  description: This is an open HTTP API specification for issuing Verifiable Credentials based on the W3C Verifiable Credentials Data Model (https://www.w3.org/TR/vc-data-model/). Implementations of this API may differ in terms of which representation formats or proof formats they do or do not support.
  version: "0.0.2"
  title: Verifiable Credential Issuer HTTP API
  contact:
    email: george.aristy@securekey.com
  license:
    name: All documents in this Repository are licensed by contributors under the [W3C Software and Document License](http://www.w3.org/Consortium/Legal/copyright-software).
paths:
  /credentials/sign:
    post:
      summary: Constructs a credential from a template, attaches proof, and returns it in the response body.
      operationId: signCredential
      description: Signs a credential and returns it in the response body. Support of this part of the API is REQUIRED for implementations.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignCredentialRequest'
        description: Parameters for constructing and issuing the credential.
      responses:
        '201':
          description: Credential was successfully issued.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialResponse'
        '400':
          description: Malformed request from client.
        '500':
          description: Internal error
  /credentials/construct:
    post:
      summary: Constructs a credential from pre-configured templates and returns it in the response body.
      operationId: constructCredential
      description: Constructs and issues a credential and returns it in the response body. Support of this part of the API is REQUIRED for implementations.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConstructCredentialRequest"
        description: Parameters for signing and issuing the credential.
      responses:
        '201':
          description: Credential was successfully issued.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialResponse'
        '400':
          description: Malformed request from client.
        '500':
          description: Internal error
  /credentials/{credentialReference}/status:
    post:
      summary: Changes the credential status.
      operationId: changeCredentialStatus
      description: Changes the credential status. Support of this part of the API is REQUIRED for implementations.
      parameters:
        - in: path
          required: true
          name: credentialReference
          schema:
            type: string
          description: Reference to a credential that has been issued.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeStatusRequest'
        description: Parameters for changing the credential status.
      responses:
        '200':
          description: credential status successfully changed!
        '400':
          description: invalid input!
        '404':
          description: credential not found!
        '500':
          description: error!
        '501':
          description: not supported by this implementation!
components:
  schemas:
    ConstructCredentialRequest:
      type: object
      required:
        - issuer
        - vcTemplateReference
        - claims
        - output
      properties:
        issuer:
          type: string
          description: A reference to the issuer's pre-configured profile.
        vcTemplateReference:
          type: string
          description: A reference to the pre-configured Verifiable Credential template.
        claims:
          type: array
          description: A set of claims about one or more subjects.
          items:
            $ref: '#/components/schemas/Claims'
        output:
          $ref: '#/components/schemas/Output'
      example: {
        "issuer": "did:example:123456677",
        "vcTemplateReference": "https://issuer.oidp.uscis.gov/schemas/v1/prcard",
        "claims": [{
          "sub": "did:example:123456abcdefg",
          "givenName": "JOHN",
          "familyName": "SMITH",
          "gender": "Male",
          "image": "data:image/png;base64,iVBORw0KGgo...kJggg==",
          "residentSince": "2015-01-01",
          "lprCategory": "C09",
          "lprNumber": "999-999-999",
          "commuterClassification": "C1",
          "birthCountry": "Bahamas",
          "birthDate": "1958-07-17"
        }],
        "output": {
          "encoding": "jsonld",
          "encodingOptions": {
            "suite": "JsonWebSignature2020",
            "alg": "ES256"
          }
        }
      }
    SignCredentialRequest:
      type: object
      required:
        - issuer
        - credential
        - output
      properties:
        issuer:
          type: string
          description: A reference to the issuer's identifier.
        credential:
          type: object
          description: The credential to be issued minus the proofs
        output:
          $ref: '#/components/schemas/Output'
      example: {
        "issuer": "did:example:1234567",
        "credential": {
          "credential": {
            "@context": [
              "https://www.w3.org/2018/credentials/v1",
              "https://w3id.org/citizenship/v1"
            ],
            "id": "https://issuer.oidp.uscis.gov/credentials/83627465",
            "type": [
              "VerifiableCredential",
              "PermanentResidentCard"
            ],
            "issuanceDate": "2019-12-03T12:19:52Z",
            "expirationDate": "2029-12-03T12:19:52Z",
            "credentialSubject": {
              "id": "did:example:b34ca6cd37bbf23",
              "type": [
                "PermanentResident",
                "Person"
              ],
              "givenName": "JOHN",
              "familyName": "SMITH",
              "gender": "Male",
              "image": "data:image/png;base64,iVBORw0KGgo...kJggg==",
              "residentSince": "2015-01-01",
              "lprCategory": "C09",
              "lprNumber": "999-999-999",
              "commuterClassification": "C1",
              "birthCountry": "Bahamas",
              "birthDate": "1958-07-17"
            }
          }
        },
        "output": {
          "encoding": "jsonld",
          "encodingOptions": {
            "suite": "JsonWebSignature2020",
            "alg": "ES256"
          }
        }
      }
    CredentialResponse:
      type: object
      properties:
        credentialReference:
          type: string
          description: Reference to the issued credential.
        credential:
          description: Encoded credential.
          oneOf:
            - type: string
            - type: object
    Claims:
      type: object
      description: A set of claims about a single subject. A claim without properties other than 'sub' MUST be rejected.
      additionalProperties: true
      required:
        - sub
      properties:
        sub:
          type: string
          description: Subject of these claims.
          example: did:example:123456abcdefg
    Output:
      type: object
      description: Output encoding options.
      required:
        - encoding
        - encodingOptions
      properties:
        encoding:
          type: string
          enum:
            - jsonld
            - jwt
        encodingOptions:
          oneOf:
            - $ref: '#/components/schemas/JSONLDEncoding'
            - $ref: '#/components/schemas/JWTEncoding'
    JSONLDEncoding:
      type: object
      description: Verifiable Credential encoded as a JSON-LD object with an embedded proof.
      additionalProperties: true
      required:
        - suite
      properties:
        suite:
          type: string
          description: Linked Data Cryptographic Suite.
    JWTEncoding:
      type: object
      description: Verifiable Credential encoded as a signed JWT.
      additionalProperties: true
      required:
        - alg
      properties:
        alg:
          type: string
          description: JWS algorithm.
    ChangeStatusRequest:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          description: New status of the credential. Well-known values are "revoked", "suspended", "active". Other values MAY be supported.
          example: revoked
        reason:
          type: string
          description: Optional reason statement for the new status of the credential.
          example: Disciplinary action
        options:
          type: object
          additionalProperties: true
          description: Optional object containing additional options for the new status of the credential.
          example: {}
